version: "3.9"

services:
  api:
    image: pom-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    # environment:
    #   ASPNETCORE_URLS: "http://+:5000"
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  postgres:
    image: postgres:16.2-alpine
    restart: always
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "pom"
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
